### ISSUE TITLE
What is this, you don't have a README.md

### ISSUE THREAD

**Issue by Python-Sargent** [WesleyWeinberg/Rcscap#1]
Not to be in the way, but why don't you have a readme file?
It would be really helpful for viewers.

**Comment by WesleyWeinberg** [comment]
Still making the website for my squadron. Will add a readme and documentation of the site once it's done so it can be maintained when I'm gone. But as I'm the only one working on it rn it's not a large issue. it is just a Django site, gonna host it on python anywhere, uses basic HTML and CSS, and will work on WebGL and JS later...

**Comment by Python-Sargent** [comment]
What do you mean? I can't read your typing :wink:

**Comment by WesleyWeinberg** [comment]
Do you use a java script web frame work like vue.js, or ruby on rails, or
something like that? to host your websites?

**Comment by Python-Sargent** [comment]
No, I don't generally host anything, I've started using Node.js for a
private project though.
